# Cloudflare Workers configuration
name = "filtering"
main = "src/worker.js"
compatibility_date = "2023-12-01"

[env.production]
name = "filtering"
route = "https://kbnote.online"
zone_id = "e5f4139af9ab971eff1d739cce6d2d54"

[[kv_namespaces]]
binding = "ANTI_BOT_KV"
id = "009ad6dea9ed48cea0573d30207fe937"


[vars]
TURNSTILE_SITE_KEY = "0x4AAAAAABlZpUYDUKYDODho"
LANDING_URL = "https://your-landing-page.com"

[secrets]
TURNSTILE_SECRET_KEY = "0x4AAAAAABlZpVdzI9lofsMHx0mGnL8JeKA"
WEBHOOK_URL = "https://your-webhook-endpoint.com/log"
