name = "Antibot"
main = "src/worker.js"
compatibility_date = "2024-07-18"
node_compat = true

[env.production]
zone_id = ""
account_id = ""

# Cache & Config Storage
[[kv_namespaces]]
binding = "ANTI_BOT_KV"
id = "NEW_KV_ID_FOR_ANTI_BOT_KV"

[[kv_namespaces]]
binding = "ACCESS_LOGS"
id = "NEW_KV_ID_ACCES_LOGS"  

[[kv_namespaces]]
binding = "ERROR_LOGS"
id = "NEW_KV_ID_ERROR_LOGS"  

[[kv_namespaces]]
binding = "CONFIG_KV"
id = "NEW_KV_ID_FOR_CONFIG"       

# D1 Databases
[[d1_databases]]
binding = "CACHE_DB"
database_name = "antibot-cache"
database_id = "NEW_D1_ID_FOR_CACHE" 

[[d1_databases]]
binding = "ANALYTICS_DB"
database_name = "antibot-analytics"
database_id = "NEW_D1_ID_FOR_ANALYTICS" 

# Environment Variables
[vars]
TURNSTILE_SITE_KEY = ""
TURNSTILE_SECRET_KEY = "" 
HASH_SALT = ""   
LANDING_URL = "https://your-landing-page.com"
MAX_FAILED_CHALLENGES = "5"
