name = "filtering"
main = "src/worker.js"
compatibility_date = "2023-12-01"

# Multiple routes (multi-host, multi-subdomain)

# Default environment settings
[env.production]
name = "filtering"
zone_id = "" # Zone ID dari salah satu domain, biasanya cukup satu saja
account_id = ""

# KV Namespace
[[env.production.kv_namespaces]]
binding = "ANTI_BOT_KV"
id = ""

# Vars (Environment Variables)
[env.production.vars]
TURNSTILE_SITE_KEY = ""
LANDING_URL = "https://landing-test-page.com"

[observability.logs]
enabled = true
